// Pure value-detection library — detector registry + codecs, zero React
// and zero Monaco. The workbench edit affordances (useValueEditAction,
// modals) and the panel's read-only introspection both build on this.

export { COMPACT_VALUE_TITLES, compactDecodedText, encodeDetectedValue } from './compact-codec';
export {
  type DetectedAcceptList,
  type DetectedAuthParams,
  type DetectedBase64,
  type DetectedCacheControl,
  type DetectedContentDisposition,
  type DetectedCookie,
  type DetectedCsp,
  type DetectedDataUri,
  type DetectedHex,
  type DetectedHsts,
  type DetectedHttpDate,
  type DetectedJsonString,
  type DetectedJsonValue,
  type DetectedJWT,
  type DetectedLinkHeader,
  type DetectedQueryString,
  type DetectedTimestamp,
  type DetectedUrlEncoded,
  type DetectedValue,
  detectValueType,
} from './detect';
export {
  type DecodedBase64,
  type DecodedDataUri,
  type DecodedHex,
  type DecodedJsonValue,
  type DecodedTimestamp,
  encodeBase64,
  encodeCookieList,
  encodeCspList,
  encodeDataUri,
  encodeHex,
  encodeJsonString,
  encodeJsonValue,
  encodeTimestamp,
  tryDecodeBase64,
  tryDecodeCookieList,
  tryDecodeCspList,
  tryDecodeDataUri,
  tryDecodeHex,
  tryDecodeJsonString,
  tryDecodeJsonValue,
  tryDecodeTimestamp,
  tryDecodeUrlComponent,
} from './encodings';
export {
  type DecodedAuthParams,
  encodeAcceptList,
  encodeAuthParams,
  encodeCacheControl,
  encodeContentDisposition,
  encodeHsts,
  encodeHttpDate,
  encodeLinkHeader,
  encodeQueryString,
  tryDecodeAcceptList,
  tryDecodeAuthParams,
  tryDecodeCacheControl,
  tryDecodeContentDisposition,
  tryDecodeHsts,
  tryDecodeHttpDate,
  tryDecodeLinkHeader,
  tryDecodeQueryString,
} from './header-values';
export {
  type DecodedJWT,
  decodeJWT,
  encodeJWT,
  formatJSON,
  getJWTExpiration,
  isJWT,
  JWT_CLAIM_DESCRIPTIONS,
  type JWTExpirationInfo,
  validateJSON,
} from './jwt';
export { type JwtScanHit, scanForJWTs } from './scan';
