export type {
  AppUpdateInfo,
  Capabilities,
  CapabilityName,
  InstallTargetBrowser,
  NmAutoPairResult,
  NmHostPresenceVerdict,
  PairWithCodeInput,
  PairWithCodeResult,
  RequestRuntimeKind,
  TerminalHostApi,
  TerminalSession,
  TerminalSpawnOptions,
  TerminalSpawnProfile,
  WhatsNewHistoryApi,
  WorkspaceMemberCandidate,
  WorkspaceMemberRow,
  WorkspaceMembersApi,
  WorkspaceMembersListResult,
  WorkspaceMembersMutationResult,
  WorkspacePublicShareApi,
  WorkspacePublicShareMutationResult,
  WorkspacePublicSharePreview,
  WorkspacePublicShareStatus,
} from './registry';
export {
  getCapability,
  hasCapability,
  registerCapability,
  unregisterCapability,
} from './registry';
