export type {
  JsonArray,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  OperationResult,
} from './common';
export { errorMessage, toError } from './common';
export type {
  ConsoleArg,
  ConsoleArgObject,
  ConsoleRecord,
  CookieAttributes,
  DomNode,
  NavigationEntry,
  NetworkRecord,
  NetworkTimingData,
  PageTransition,
  PreprocessedRecording,
  PreprocessOptions,
  PreprocessProgressDetails,
  RawRecordingRecord,
  Recording,
  RecordingEvent,
  RecordingEventData,
  RecordingMetadata,
  RRWebAdd,
  RRWebEvent,
  RRWebInnerData,
  RRWebPlayerConstructor,
  RRWebPlayerInstance,
  RRWebPlayerProps,
  Snapshot,
  StaticResources,
  StorageCookieMetadata,
  StorageRecord,
  TimeEvent,
  TimeEventType,
  WorkflowRecordingEntry,
  WorkflowRecordingFileMetadata,
  WorkflowTag,
} from './recording';

// ── v5 types (new data model) ──────────────────────────────────────
export * as V5 from './v5';
