/**
 * Importers — curl (v1), HAR / Postman / Insomnia / OpenAPI (v2+).
 *
 * Every importer produces an `ImportReport` alongside the imported
 * entities so users can audit drops/transforms per ARCHITECTURE.md §23.
 */

export {
  buildPullPlan,
  classifyPullFailure,
  collectionUrl,
  DEFAULT_RETRY_AFTER_SECONDS,
  ENUMERATION_CALL_SPACING_MS,
  environmentUrl,
  foldPullEvent,
  type HeaderLookup,
  type Interpreted,
  ITEM_CALL_SPACING_MS,
  initialPullRunState,
  MAX_RATE_LIMIT_RETRIES,
  type MigrationPullRunPhase,
  type MigrationPullRunState,
  POSTMAN_API_KEY_HEADER,
  POSTMAN_DATA_API_ORIGIN,
  type PostmanImportedWorkspace,
  type PostmanImportSummary,
  type PostmanPullEvent,
  type PostmanPullOutcome,
  type PostmanPullPlan,
  type PostmanPullResult,
  type PostmanPullSkip,
  type PostmanWorkspaceListResult,
  type PostmanWorkspacePreview,
  type PulledCollection,
  type PulledEnvironment,
  type PulledPayload,
  type PullFailure,
  type PullFailureKind,
  type PullPlanItem,
  type PullRateBudget,
  type PullWorkspaceSummary,
  readCollectionPayload,
  readEnvironmentPayload,
  readRateBudget,
  readWorkspaceDetail,
  readWorkspaceList,
  startPullRunState,
  type WorkspaceDetail,
  type WorkspaceItemRef,
  type WorkspaceListRead,
  workspaceDetailUrl,
  workspaceListUrl,
} from './api-pull';
export {
  type BrunoFile,
  type BrunoParsedEnvironment,
  type BrunoParsedEnvironmentVariable,
  type BrunoParsedFolder,
  type BrunoParsedRequest,
  BrunoParseError,
  type BrunoParseResult,
  isBrunoImportPath,
  parseBruno,
  parseBrunoFiles,
  stripBrunoRootPrefix,
} from './bruno';
export {
  CurlParseError,
  type CurlParseResult,
  type CurlRequest,
  type ImportedRequestSettings,
  parseCurl,
  tokenize,
} from './curl';
export {
  type DataScanInterpretation,
  type DataScanSkip,
  type DataScanStore,
  type DataScanTarget,
  type InsomniaNedbFinding,
  interpretDataScanFiles,
  interpretInsomniaStores,
  interpretPostmanBackups,
  listDataScanTargets,
  matchesDataScanFile,
  type PostmanBackupFinding,
  parseNedbLines,
  type ScannedFile,
  type ToolDataFinding,
} from './data-scan';
export { type DetectedImportSource, detectImportSource } from './detect';
export {
  diffImportReports,
  type ImportReportDiff,
  type ImportSummaryDelta,
  type ReportDiffPartition,
} from './diff';
export {
  convertHarRequest,
  type HarParsedEntry,
  HarParseError,
  type HarParseResult,
  type HarRequest,
  parseHar,
  selectHarEntries,
} from './har';
export {
  flattenEnvironmentData,
  type InsomniaParsedCollection,
  type InsomniaParsedEnvironment,
  type InsomniaParsedEnvironmentVariable,
  type InsomniaParsedFolder,
  type InsomniaParsedRequest,
  InsomniaParseError,
  type InsomniaParseResult,
  parseInsomnia,
  parseInsomniaDocs,
  rewriteTemplateRefs,
} from './insomnia';
export {
  type InstallProbe,
  type InstallProbePlatform,
  type InstallProbeResult,
  type InstallProbeRoots,
  listInstallProbes,
  MIGRATION_TOOL_NAMES,
  MIGRATION_TOOLS,
  type MigrationTool,
  resolveInstallFindings,
  type ToolInstallFinding,
} from './install-detect';
export {
  type PostmanCollectionVariable,
  type PostmanEnvironmentParseResult,
  type PostmanParsedEnvironmentVariable,
  type PostmanParsedExample,
  type PostmanParsedFolder,
  type PostmanParsedRequest,
  PostmanParseError,
  type PostmanParseOptions,
  type PostmanParseResult,
  parsePostman,
  parsePostmanEnvironment,
} from './postman';
export {
  type PostmanBackupCounts,
  type PostmanBackupParsedPreset,
  PostmanBackupParseError,
  type PostmanBackupParseResult,
  parsePostmanBackup,
} from './postman-backup';
export {
  type CreateWorkspaceExportReportInput,
  createReport,
  createWorkspaceExportReport,
  FLAT_IMPORT_SOURCES,
  type FlatImportReport,
  FlatImportReportSchema,
  hashImportSource,
  IMPORT_SOURCES,
  IMPORT_TARGET_MODES,
  type ImportDrop,
  ImportDropSchema,
  type ImportReport,
  ImportReportSchema,
  type ImportSource,
  ImportSourceSchema,
  type ImportSummary,
  ImportSummarySchema,
  type ImportTargetMode,
  ImportTargetModeSchema,
  type ImportTransform,
  ImportTransformSchema,
  MISSING_DEP_TYPES,
  type MissingDep,
  MissingDepSchema,
  type MissingDepType,
  MissingDepTypeSchema,
  type PerEntityStrategies,
  PerEntityStrategiesSchema,
  recordDrop,
  recordTransform,
  type WorkspaceExportImportReport,
  WorkspaceExportImportReportSchema,
} from './report';
