export type {
  AppUpdatePhase,
  AppUpdateSeverity,
  AppUpdateState,
  BridgeBroadcastContract,
  BridgeBroadcastPayload,
  BridgeBroadcastType,
  BridgeMessageType,
  BridgeRpcContract,
  BridgeRpcRequest,
  BridgeRpcResponse,
  BridgeRpcType,
  BridgeTabContract,
  BridgeTabRequest,
  BridgeTabResponse,
  BridgeTabType,
  CacheEntryDocumentWire,
  CacheEntryHeaderWire,
  CacheEntryWire,
  CacheStorageCacheWire,
  CookieJarEntryWire,
  DomStorageAreaWire,
  DomStorageEntryWire,
  DomStorageRenameFailureWire,
  EnvironmentsSnapshot,
  FolderDescriptor,
  GrpcStreamEventWire,
  GrpcStreamMessageWire,
  IdbDatabaseWire,
  IdbObjectStoreWire,
  IdbRecordDocumentWire,
  IdbRecordPreviewEntryWire,
  IdbRecordPreviewNodeWire,
  IdbRecordWire,
  IdbRecordWriteFailureWire,
  JarCookieEditWire,
  JarCookieKeyWire,
  JarCookieWire,
  LiveWorkflowRunSnapshot,
  MigrationPullStartResult,
  MigrationReadBackupResult,
  MigrationReadInsomniaDataResult,
  MigrationScanResult,
  ProductTelemetryLogEntryWire,
  ProductTelemetrySnapshot,
  RequestStreamEventWire,
  RequestStreamHeadWire,
  SecretsStorageState,
  SiteDataTypeWire,
  SiteJarCookieWire,
  StorageInvalidationKind,
  StorageQuotaBreakdownWire,
  StorageQuotaWire,
  StorageScopeWire,
  WorkspaceSnapshot,
  WorkspaceTreeCommitCadence,
  WorkspaceTreeGitStatusWire,
  WorkspaceTreePullWire,
  WsSendSocketIoWire,
  WsStreamEventWire,
  WsStreamMessageWire,
} from '../protocol/channels';

// The typed channel registry the `HostBridge` contract is generic over.
// Physically lives in `../protocol/channels.ts` (alongside the other
// wire-shape `*-bridge.ts` files); surfaced here so `@openheaders/core/
// bridge` is the single entry point for everything bridge-related.
export { BridgeError } from '../protocol/channels';
export {
  getHostBridge,
  type HostBridge,
  hostBridge,
  requireHostBridge,
  setHostBridge,
} from './host-bridge';
