/**
 * Git plane (GIT_PLAN.md Phase 3+) — system-binary execution seam,
 * repo init/adopt, temp-index commits, identity resolution, and the
 * porcelain status feeds. Consumed by the workspace-tree runtime;
 * never by surfaces (they reach the git plane via gesture RPCs, §8).
 */

export {
  type BranchCreateResult,
  type BranchDeleteResult,
  type BranchUpdateResult,
  type CreateLocalBranchOptions,
  createLocalBranch,
  deleteLocalBranch,
  type FetchAllRemotesResult,
  fetchAllRemotes,
  listCommitRangeLog,
  updateBranchFromUpstream,
} from './branch-ops';
export { isStateChanging, subcommandOf } from './audit-classify';
export { type CommitIntent, composeCommitMessage } from './commit-message';
export {
  type AddIgnoreEntryResult,
  addIgnoreEntry,
  checkIgnoreProvenance,
  type IgnoreProvenance,
  type IgnoreTarget,
  type RemoveIgnoreEntryResult,
  removeIgnoreEntry,
} from './ignore-ops';
export {
  type CreateGitExecOptions,
  createGitExec,
  GIT_VERSION_FLOOR,
  type GitAuditRow,
  type GitAvailability,
  type GitExecOptions,
  type GitExecResult,
  type GitRunner,
  probeGitAvailability,
} from './git-exec';
export {
  type BranchOpResult,
  COMMIT_FILE_DIFF_MAX_BYTES,
  type CommitFileDiff,
  type CommitFileDiffResult,
  type CommitLogEntry,
  type CommitLogFileChange,
  type CommitLogFilters,
  type CommitUserAttribution,
  type CommitWorkspaceTreeOptions,
  type CommitWorkspaceTreeResult,
  type CreateRescueBranchResult,
  checkoutWorkspaceBranch,
  cleanUntracked,
  commitParents,
  commitWorkspaceTree,
  countDirtyFiles,
  countLeftRight,
  createAndSwitchBranch,
  createRescueBranch,
  currentBranch,
  diffForeignPaths,
  type EnsureWorkspaceRepoResult,
  ensureWorkspaceRepo,
  type FastForwardResult,
  type FetchWorkspaceRemoteResult,
  type ForeignTreeDiff,
  fastForwardWorkspaceBranch,
  fetchWorkspaceRemote,
  gitOperationInProgress,
  isAncestorOf,
  isCommitSha,
  isSafeRefName,
  isSafeTreePath,
  isWorkspaceRepo,
  type LeftRightCounts,
  listCommitLog,
  listFileLog,
  listForeignAuthors,
  listLocalBranches,
  listRepoRefs,
  listTreeYamlPaths,
  listWorkingChanges,
  localHeadSha,
  mergeBaseOf,
  type PushWorkspaceBranchResult,
  parsePorcelainCount,
  parseWorkingChanges,
  pushHeadToNewBranch,
  pushWorkspaceBranch,
  type RepoRef,
  type ResolvedCommitIdentity,
  readCommitFileDiff,
  readCommitTreeFiles,
  readWorkingFileDiff,
  resolveAuthorFilterValue,
  resolveCommitIdentity,
  resolveRefSha,
  resolveUpstream,
  type SyntheticCommitIdentity,
  stashWorkspaceTree,
  type UpstreamState,
  userIndexHasStagedChanges,
  type WorkingChange,
  withCommitAttribution,
} from './repo';
