/**
 * `@openheaders/core/telemetry` — anonymous product-analytics vocabulary
 * (typed allowlist), fire-and-forget client, and the host controller
 * that gates it (`TELEMETRY_PLAN.md`). Zero platform deps; hosts inject
 * transport/session/gate seams and drive flush cadence, UI surfaces only
 * call `track()` over the bridge.
 */

export {
  buildTelemetryUninstallUrl,
  mintTelemetryInstallId,
  mintTelemetrySessionId,
  type PersistedTelemetryQueueEntry,
  PRODUCT_TELEMETRY_ENDPOINT,
  PRODUCT_TELEMETRY_UNINSTALL_ENDPOINT,
  TELEMETRY_MAX_LOG,
  TELEMETRY_MAX_QUEUE,
  TelemetryClient,
  type TelemetryClientDeps,
  type TelemetryDisposition,
  type TelemetryEnvelopeFacts,
  type TelemetryInstallContext,
  type TelemetryLogEntry,
  type TelemetryQueueStore,
  type TelemetryTransport,
} from './client';
export {
  createInMemoryProductTelemetryInstallStore,
  createInMemoryProductTelemetrySessionStore,
  oncePerSessionLatchKey,
  ProductTelemetryController,
  type ProductTelemetryControllerDeps,
  type ProductTelemetryInstallStore,
  type ProductTelemetrySessionStore,
  SESSION_START_LATCH_KEY,
  SESSION_START_SENT_LATCH_KEY,
} from './controller';
export {
  activatedPlanFromLicenseSnapshot,
  bucketScale,
  bucketSessionAge,
  bucketSinceInstall,
  parseTelemetryAppVersion,
  TELEMETRY_SCHEMA_VERSION,
  type TelemetryAppVersion,
  TelemetryAppVersionSchema,
  type TelemetryBrowserKind,
  TelemetryBrowserKindSchema,
  type TelemetryChannelId,
  TelemetryChannelIdSchema,
  type TelemetryEnvelope,
  TelemetryEnvelopeSchema,
  type TelemetryErrorCode,
  TelemetryErrorCodeSchema,
  type TelemetryEvent,
  TelemetryEventSchema,
  type TelemetryFeatureId,
  TelemetryFeatureIdSchema,
  type TelemetryHostKind,
  TelemetryHostKindSchema,
  type TelemetryImportSourceId,
  TelemetryImportSourceIdSchema,
  TelemetryInstallIdSchema,
  type TelemetryLocale,
  TelemetryLocaleSchema,
  type TelemetryMonetizationSurface,
  TelemetryMonetizationSurfaceSchema,
  type TelemetryPlanBucket,
  TelemetryPlanBucketSchema,
  type TelemetryPlatform,
  TelemetryPlatformSchema,
  type TelemetryRuleCreatedOrigin,
  TelemetryRuleCreatedOriginSchema,
  type TelemetryRuleTypeId,
  TelemetryRuleTypeIdSchema,
  type TelemetryScaleBucket,
  TelemetryScaleBucketSchema,
  type TelemetrySessionAgeBucket,
  TelemetrySessionAgeBucketSchema,
  TelemetrySessionIdSchema,
  type TelemetrySinceInstallBucket,
  TelemetrySinceInstallBucketSchema,
  type TelemetryUninstallReason,
  TelemetryUninstallReasonSchema,
  toTelemetryLocale,
} from './vocabulary';
